

INSERT INTO `countries` VALUES (1, 'AF', 'Afganistán',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (2, 'AL', 'Alemania',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (3, 'AS', 'Arabia Saudita',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (4, 'AR', 'Argentina',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (5, 'AU', 'Australia',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (6, 'BE', 'Bélgica',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (7, 'BO', 'Bolivia',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (8, 'BR', 'Brasil',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (9, 'CA', 'Camboya',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (10,'CA', 'Canadá',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (11, 'CH', 'Chile',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (12, 'CI', 'China',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (13, 'AM', 'Colombia',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (14, 'AW', 'Corea',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (15, 'AU', 'Costa Rica',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (16, 'AT', 'Cuba',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (17, 'AZ', 'Dinamarca',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (18, 'BS', 'Ecuador',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (19, 'BH', 'Egipto',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (20, 'BD', 'El Salvador',NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (21, 'BB', 'España', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (22, 'BY', 'Estados Unidos', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (23, 'BE', 'Estonia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (24, 'BZ', 'Etiopia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (25, 'BJ', 'Filipinas', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (26, 'BM', 'Finlandia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (27, 'BT', 'Francia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (28, 'BO', 'Gales', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (29, 'BA', 'Grecia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (30, 'BW', 'Guatemala', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (31, 'BV', 'Haití', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (32, 'BR', 'Holanda', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (33, 'IO', 'Honduras', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (34, 'BN', 'Indonesia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (35, 'BG', 'Inglaterra', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (36, 'BF', 'Irlanda', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (37, 'BI', 'Israel', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (38, 'KH', 'Italia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (39, 'CM', 'Japón', NULL, NULL, NULL, NULL,1);
INSERT INTO `countries` VALUES (40, 'CV', 'Jordania', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (41, 'KY', 'Laos', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (42, 'CF', 'Letonia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (43, 'TD', 'Lituania', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (44, 'CL', 'Malasia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (45, 'CN', 'Marrueco', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (46, 'CX', 'México', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (47, 'CC', 'Nicaragua', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (48, 'CO', 'Noruega', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (49, 'KM', 'Nueva Zelanda', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (50, 'CG', 'Panamá', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (51, 'CK', 'Paraguay', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (52, 'CR', 'Perú', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (53, 'HR', 'Polonia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (54, 'CU', 'Portugal', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (55, 'CY', 'Puerto Rico', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (56, 'CZ', 'Republica Dominicana', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (57, 'DK', 'Rumania', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (58, 'DJ', 'Rusia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (59, 'DM', 'Suecia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (60, 'DO', 'Suiza', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (61, 'TP', 'Tailandia', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (62, 'EC', 'Taiwán', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (63, 'EG', 'Turquía', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (64, 'SV', 'Ucrania', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (65, 'GQ', 'Uruguay', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (66, 'ER', 'Venezuela', NULL, NULL,NULL, NULL, 1);
INSERT INTO `countries` VALUES (67, 'EE', 'Vietnam', NULL, NULL,NULL, NULL, 1);



INSERT INTO `nationalities` VALUES (1, 'Afgano', 1, NULL, NULL,NULL, NULL, 1);
INSERT INTO `nationalities` VALUES (2, 'Alemán', 2, NULL, NULL,NULL, NULL, 1);
INSERT INTO `nationalities` VALUES (3, 'Árabe', 3, NULL, NULL,NULL, NULL, 1);
INSERT INTO `nationalities` VALUES (4, 'Argentino', 4, NULL, NULL,NULL, NULL, 1);
INSERT INTO `nationalities` VALUES (5, 'Australiano', 5, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (6, 'Belga', 6, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (7, 'Boliviano', 7, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (8, 'Brasilero', 8, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (9, 'Camboyano', 9, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (10, 'Canadiense', 10, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (11, 'Chileno', 11, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (12, 'Chino', 12, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (13, 'Colombiano', 13, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (14, 'Coreano', 14, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (15, 'Costarricense', 15, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (16, 'Cubano', 16, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (17, 'Danés', 17, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (18, 'Ecuatoriano', 18, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (19, 'Egipcio', 19, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (20, 'Salvadoreño', 20, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (21, 'Español', 21, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (22, 'Estadounidense', 22, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (23, 'Estonio', 23, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (24, 'Etiope', 24, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (25, 'Filipino', 25, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (26, 'Finlandés', 26, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (27, 'Francés', 27, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (28, 'Galés', 28, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (29, 'Griego', 29, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (30, 'Guatemalteco', 30, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (31, 'Haitiano', 31, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (32, 'Holandés', 32, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (33, 'Hondureño', 33, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (34, 'Indonés', 34, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (35, 'Inglés', 35, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (36, 'Irlandés', 36, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (37, 'Israelí', 37, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (38, 'Italiano', 38, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (39, 'Japonés', 39, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (40, 'Jordano', 40, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (41, 'Laosiano', 41, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (42, 'Letón', 42, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (43, 'Letonés', 43, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (44, 'Malayo', 44, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (45, 'Marroquí', 45, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (46, 'Mexicano', 46, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (47, 'Nicaragüense', 47, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (48, 'Noruego', 48, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (49, 'Neocelandés', 49, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (50, 'Panameño', 50, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (51, 'Paraguayo', 51, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (52, 'Peruano', 52, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (53, 'Polaco', 53, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (54, 'Portugués', 54, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (55, 'Puertorriqueño', 55, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (56, 'Dominicano', 56, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (57, 'Rumano', 57, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (58, 'Ruso', 58, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (59, 'Sueco', 59, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (60, 'Suizo', 60, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (61, 'Tailandés', 61, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (62, 'Taiwanes', 62, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (63, 'Turco', 63, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (64, 'Ucraniano', 64, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (65, 'Uruguayo', 65, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (66, 'Venezolano', 66, NULL, NULL,NULL, NULL,1);
INSERT INTO `nationalities` VALUES (67, 'Vietnamita', 67, NULL, NULL,NULL, NULL,1);
