<?php

use Database\TruncateTable;
use Carbon\Carbon as Carbon;
use Illuminate\Database\Seeder;
use Database\DisableForeignKeys;
use Illuminate\Support\Facades\DB;

class CountrieTableSeeder extends Seeder
{
    use DisableForeignKeys, TruncateTable;

    /**
     * Run the database seed.
     *
     * @return void
     */
    public function run()
    {
        $this->disableForeignKeys();
        $this->truncate('countries');
 
        $country =  [
            [
                'code'              => 'AF',
                'name'              => 'Afganistán',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AL',
                'name'              => 'Alemania',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AR',
                'name'              => 'Argentina',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AU',
                'name'              => 'Australia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'BE',
                'name'              => 'Bélgica',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'BO',
                'name'              => 'Bolivia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'BR',
                'name'              => 'Brasil',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Camboya',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Canadá',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Chile',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'China',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Colombia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Corea',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Costa Rica',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Cuba',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Dinamarca',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Ecuador',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Egipto',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'El Salvador',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'España',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Estados Unidos',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Estonia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Etiopia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Filipinas',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Finlandia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Francia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Gales',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Grecia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Guatemala',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Haití',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Holanda',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Honduras',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Indonesia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Inglaterra',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Irlanda',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Israel',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Italia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Japón',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Jordania',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Laos',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Letonia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Lituania',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Malasia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Marrueco',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'México',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Nicaragua',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Noruega',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Nueva Zelanda',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Panamá',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Paraguay',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Perú',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Polonia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Portugal',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Puerto Rico',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Republic Dominicana',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Rumania',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Rusia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Suecia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Suiza',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Tailandia',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Taiwán',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Turquía',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Ucrania',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Uruguay',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Venezuela',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            [
                'code'              => 'AF',
                'name'              => 'Vietnam',
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
                'created_user_id'   => 2,
                'updated_user_id'   => 2,
            ],
            ];

        DB::table('countries')->insert($country);
        $this->enableForeignKeys();
    }
}
